# Generated by Django 5.2.8 on 2025-12-01 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='label_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
