# Generated by Django 5.2.8 on 2025-11-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='song_covers/'),
        ),
    ]
