# Generated by Django 5.2.8 on 2025-11-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_cover_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='catalog_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='composition_owner',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='composition_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='excluded_countries',
            field=models.CharField(blank=True, help_text='Comma-separated list of country codes to exclude', max_length=1000),
        ),
        migrations.AddField(
            model_name='song',
            name='explicit_content',
            field=models.CharField(choices=[('not_explicit', 'Not Explicit'), ('explicit', 'Explicit'), ('clean', 'Clean')], default='not_explicit', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='featured_artists',
            field=models.CharField(blank=True, help_text='Comma-separated list of featured artists', max_length=1000),
        ),
        migrations.AddField(
            model_name='song',
            name='label_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='master_recording_owner',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='master_recording_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='primary_artist_name',
            field=models.CharField(default='Unknown', help_text='Name to be displayed as primary artist', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='subgenre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='song',
            name='version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
