# Generated by Django 5.2.8 on 2025-11-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_catalog_number_song_composition_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='label_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='album',
            name='upc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
