# Generated by Django 5.2.8 on 2025-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_genre_album_is_released_album_label_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
