# Generated by Django 5.2.8 on 2025-11-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_song_is_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='producer',
            field=models.CharField(blank=True, help_text='Producer name(s)', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='song_writer',
            field=models.CharField(blank=True, help_text='Song writer name(s)', max_length=255),
        ),
    ]
