# Generated by Django 5.2.8 on 2025-11-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_song_producer_song_song_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('released', 'Released'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='release_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('released', 'Released'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
    ]
