# Generated by Django 5.2.8 on 2025-12-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_distributionrequest_created_at'),
        ('music', '0008_album_release_status_song_release_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distributionrequest',
            unique_together={('song', 'platform')},
        ),
    ]
