# Generated by Django 5.2.8 on 2025-12-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_releaserequest_releaserequestcontent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaserequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('released', 'Released')], default='pending', max_length=20),
        ),
    ]
