# Generated by Django 5.2.8 on 2025-11-28 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0002_initial'),
        ('distribution', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='music.song'),
        ),
        migrations.AddField(
            model_name='streamcount',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.platform'),
        ),
        migrations.AddField(
            model_name='streamcount',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='music.song'),
        ),
        migrations.AlterUniqueTogether(
            name='revenue',
            unique_together={('song', 'platform', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='streamcount',
            unique_together={('song', 'platform', 'date')},
        ),
    ]
