# Generated by Django 5.2.8 on 2025-12-01 02:00

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0005_paymentprovider_and_more'),
        ('distribution', '0005_distributionrequest_created_at'),
        ('music', '0008_album_release_status_song_release_status'),
        ('users', '0002_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ArtistAlbum',
            fields=[
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('music.album',),
        ),
        migrations.CreateModel(
            name='ArtistRevenueSplit',
            fields=[
            ],
            options={
                'verbose_name': 'Revenue Split',
                'verbose_name_plural': 'Revenue Splits',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('distribution.revenuesplit',),
        ),
        migrations.CreateModel(
            name='ArtistSong',
            fields=[
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('music.song',),
        ),
        migrations.CreateModel(
            name='PayoutRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Payout Request',
                'verbose_name_plural': 'Payout Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('analytics.withdrawalrequest',),
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('distribution.platform',),
        ),
        migrations.CreateModel(
            name='ReleaseRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Release Request',
                'verbose_name_plural': 'Release Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('music.song',),
        ),
        migrations.CreateModel(
            name='SystemUser',
            fields=[
            ],
            options={
                'verbose_name': 'System User',
                'verbose_name_plural': 'System Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
